/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppMistakesRouteImport } from './routes/_app/mistakes'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStyleguideRouteImport } from './routes/_app/styleguide'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminActivityRouteImport } from './routes/_app/admin/activity'
import { Route as AppAdminContentRouteImport } from './routes/_app/admin/content'
import { Route as AppAdminCostsRouteImport } from './routes/_app/admin/costs'
import { Route as AppAdminFeedbackRouteImport } from './routes/_app/admin/feedback'
import { Route as AppAdminFunnelRouteImport } from './routes/_app/admin/funnel'
import { Route as AppAdminGrowthRouteImport } from './routes/_app/admin/growth'
import { Route as AppAdminHealthRouteImport } from './routes/_app/admin/health'
import { Route as AppAdminTestsRouteImport } from './routes/_app/admin/tests'
import { Route as AppListeningIndexRouteImport } from './routes/_app/listening/index'
import { Route as AppReadingIndexRouteImport } from './routes/_app/reading/index'
import { Route as AppSpeakingIndexRouteImport } from './routes/_app/speaking/index'
import { Route as AppSpeakingLiveRouteImport } from './routes/_app/speaking/live'
import { Route as AppSpeakingSessionRouteImport } from './routes/_app/speaking/session'
import { Route as AppWritingIndexRouteImport } from './routes/_app/writing/index'
import { Route as AppWritingFullRouteImport } from './routes/_app/writing/full'
import { Route as AppAdminReplaysIndexRouteImport } from './routes/_app/admin/replays.index'
import { Route as AppAdminReplaysSessionIdRouteImport } from './routes/_app/admin/replays.$sessionId'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users.index'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users.$userId'
import { Route as AppLrResultAttemptIdRouteImport } from './routes/_app/lr/result.$attemptId'
import { Route as AppLrRunAttemptIdRouteImport } from './routes/_app/lr/run.$attemptId'
import { Route as AppSpeakingResultAttemptIdRouteImport } from './routes/_app/speaking/result.$attemptId'
import { Route as AppWritingResultAttemptIdRouteImport } from './routes/_app/writing/result.$attemptId'
import { Route as AppWritingTaskPromptIdRouteImport } from './routes/_app/writing/task.$promptId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStyleguideRoute = AppStyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCostsRoute = AppAdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFeedbackRoute = AppAdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFunnelRoute = AppAdminFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGrowthRoute = AppAdminGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHealthRoute = AppAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTestsRoute = AppAdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppListeningIndexRoute = AppListeningIndexRouteImport.update({
  id: '/listening/',
  path: '/listening/',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingIndexRoute = AppReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingIndexRoute = AppSpeakingIndexRouteImport.update({
  id: '/speaking/',
  path: '/speaking/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingLiveRoute = AppSpeakingLiveRouteImport.update({
  id: '/speaking/live',
  path: '/speaking/live',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingSessionRoute = AppSpeakingSessionRouteImport.update({
  id: '/speaking/session',
  path: '/speaking/session',
  getParentRoute: () => AppRoute,
} as any)
const AppWritingIndexRoute = AppWritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => AppRoute,
} as any)
const AppWritingFullRoute = AppWritingFullRouteImport.update({
  id: '/writing/full',
  path: '/writing/full',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReplaysIndexRoute = AppAdminReplaysIndexRouteImport.update({
  id: '/replays/',
  path: '/replays/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReplaysSessionIdRoute =
  AppAdminReplaysSessionIdRouteImport.update({
    id: '/replays/$sessionId',
    path: '/replays/$sessionId',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppLrResultAttemptIdRoute = AppLrResultAttemptIdRouteImport.update({
  id: '/lr/result/$attemptId',
  path: '/lr/result/$attemptId',
  getParentRoute: () => AppRoute,
} as any)
const AppLrRunAttemptIdRoute = AppLrRunAttemptIdRouteImport.update({
  id: '/lr/run/$attemptId',
  path: '/lr/run/$attemptId',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingResultAttemptIdRoute =
  AppSpeakingResultAttemptIdRouteImport.update({
    id: '/speaking/result/$attemptId',
    path: '/speaking/result/$attemptId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWritingResultAttemptIdRoute =
  AppWritingResultAttemptIdRouteImport.update({
    id: '/writing/result/$attemptId',
    path: '/writing/result/$attemptId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWritingTaskPromptIdRoute = AppWritingTaskPromptIdRouteImport.update({
  id: '/writing/task/$promptId',
  path: '/writing/task/$promptId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/bank': typeof AppBankRoute
  '/history': typeof AppHistoryRoute
  '/mistakes': typeof AppMistakesRoute
  '/privacy': typeof AppPrivacyRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/styleguide': typeof AppStyleguideRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/content': typeof AppAdminContentRoute
  '/admin/costs': typeof AppAdminCostsRoute
  '/admin/feedback': typeof AppAdminFeedbackRoute
  '/admin/funnel': typeof AppAdminFunnelRoute
  '/admin/growth': typeof AppAdminGrowthRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/tests': typeof AppAdminTestsRoute
  '/speaking/live': typeof AppSpeakingLiveRoute
  '/speaking/session': typeof AppSpeakingSessionRoute
  '/writing/full': typeof AppWritingFullRoute
  '/admin/': typeof AppAdminIndexRoute
  '/listening/': typeof AppListeningIndexRoute
  '/reading/': typeof AppReadingIndexRoute
  '/speaking/': typeof AppSpeakingIndexRoute
  '/writing/': typeof AppWritingIndexRoute
  '/admin/replays/$sessionId': typeof AppAdminReplaysSessionIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/lr/result/$attemptId': typeof AppLrResultAttemptIdRoute
  '/lr/run/$attemptId': typeof AppLrRunAttemptIdRoute
  '/speaking/result/$attemptId': typeof AppSpeakingResultAttemptIdRoute
  '/writing/result/$attemptId': typeof AppWritingResultAttemptIdRoute
  '/writing/task/$promptId': typeof AppWritingTaskPromptIdRoute
  '/admin/replays/': typeof AppAdminReplaysIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bank': typeof AppBankRoute
  '/history': typeof AppHistoryRoute
  '/mistakes': typeof AppMistakesRoute
  '/privacy': typeof AppPrivacyRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/styleguide': typeof AppStyleguideRoute
  '/': typeof AppIndexRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/content': typeof AppAdminContentRoute
  '/admin/costs': typeof AppAdminCostsRoute
  '/admin/feedback': typeof AppAdminFeedbackRoute
  '/admin/funnel': typeof AppAdminFunnelRoute
  '/admin/growth': typeof AppAdminGrowthRoute
  '/admin/health': typeof AppAdminHealthRoute
  '/admin/tests': typeof AppAdminTestsRoute
  '/speaking/live': typeof AppSpeakingLiveRoute
  '/speaking/session': typeof AppSpeakingSessionRoute
  '/writing/full': typeof AppWritingFullRoute
  '/admin': typeof AppAdminIndexRoute
  '/listening': typeof AppListeningIndexRoute
  '/reading': typeof AppReadingIndexRoute
  '/speaking': typeof AppSpeakingIndexRoute
  '/writing': typeof AppWritingIndexRoute
  '/admin/replays/$sessionId': typeof AppAdminReplaysSessionIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/lr/result/$attemptId': typeof AppLrResultAttemptIdRoute
  '/lr/run/$attemptId': typeof AppLrRunAttemptIdRoute
  '/speaking/result/$attemptId': typeof AppSpeakingResultAttemptIdRoute
  '/writing/result/$attemptId': typeof AppWritingResultAttemptIdRoute
  '/writing/task/$promptId': typeof AppWritingTaskPromptIdRoute
  '/admin/replays': typeof AppAdminReplaysIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/bank': typeof AppBankRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/mistakes': typeof AppMistakesRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/styleguide': typeof AppStyleguideRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/content': typeof AppAdminContentRoute
  '/_app/admin/costs': typeof AppAdminCostsRoute
  '/_app/admin/feedback': typeof AppAdminFeedbackRoute
  '/_app/admin/funnel': typeof AppAdminFunnelRoute
  '/_app/admin/growth': typeof AppAdminGrowthRoute
  '/_app/admin/health': typeof AppAdminHealthRoute
  '/_app/admin/tests': typeof AppAdminTestsRoute
  '/_app/speaking/live': typeof AppSpeakingLiveRoute
  '/_app/speaking/session': typeof AppSpeakingSessionRoute
  '/_app/writing/full': typeof AppWritingFullRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/listening/': typeof AppListeningIndexRoute
  '/_app/reading/': typeof AppReadingIndexRoute
  '/_app/speaking/': typeof AppSpeakingIndexRoute
  '/_app/writing/': typeof AppWritingIndexRoute
  '/_app/admin/replays/$sessionId': typeof AppAdminReplaysSessionIdRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/lr/result/$attemptId': typeof AppLrResultAttemptIdRoute
  '/_app/lr/run/$attemptId': typeof AppLrRunAttemptIdRoute
  '/_app/speaking/result/$attemptId': typeof AppSpeakingResultAttemptIdRoute
  '/_app/writing/result/$attemptId': typeof AppWritingResultAttemptIdRoute
  '/_app/writing/task/$promptId': typeof AppWritingTaskPromptIdRoute
  '/_app/admin/replays/': typeof AppAdminReplaysIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/bank'
    | '/history'
    | '/mistakes'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/styleguide'
    | '/admin/activity'
    | '/admin/content'
    | '/admin/costs'
    | '/admin/feedback'
    | '/admin/funnel'
    | '/admin/growth'
    | '/admin/health'
    | '/admin/tests'
    | '/speaking/live'
    | '/speaking/session'
    | '/writing/full'
    | '/admin/'
    | '/listening/'
    | '/reading/'
    | '/speaking/'
    | '/writing/'
    | '/admin/replays/$sessionId'
    | '/admin/users/$userId'
    | '/lr/result/$attemptId'
    | '/lr/run/$attemptId'
    | '/speaking/result/$attemptId'
    | '/writing/result/$attemptId'
    | '/writing/task/$promptId'
    | '/admin/replays/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/bank'
    | '/history'
    | '/mistakes'
    | '/privacy'
    | '/review'
    | '/settings'
    | '/styleguide'
    | '/'
    | '/admin/activity'
    | '/admin/content'
    | '/admin/costs'
    | '/admin/feedback'
    | '/admin/funnel'
    | '/admin/growth'
    | '/admin/health'
    | '/admin/tests'
    | '/speaking/live'
    | '/speaking/session'
    | '/writing/full'
    | '/admin'
    | '/listening'
    | '/reading'
    | '/speaking'
    | '/writing'
    | '/admin/replays/$sessionId'
    | '/admin/users/$userId'
    | '/lr/result/$attemptId'
    | '/lr/run/$attemptId'
    | '/speaking/result/$attemptId'
    | '/writing/result/$attemptId'
    | '/writing/task/$promptId'
    | '/admin/replays'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/admin'
    | '/_app/bank'
    | '/_app/history'
    | '/_app/mistakes'
    | '/_app/privacy'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/styleguide'
    | '/_app/'
    | '/_app/admin/activity'
    | '/_app/admin/content'
    | '/_app/admin/costs'
    | '/_app/admin/feedback'
    | '/_app/admin/funnel'
    | '/_app/admin/growth'
    | '/_app/admin/health'
    | '/_app/admin/tests'
    | '/_app/speaking/live'
    | '/_app/speaking/session'
    | '/_app/writing/full'
    | '/_app/admin/'
    | '/_app/listening/'
    | '/_app/reading/'
    | '/_app/speaking/'
    | '/_app/writing/'
    | '/_app/admin/replays/$sessionId'
    | '/_app/admin/users/$userId'
    | '/_app/lr/result/$attemptId'
    | '/_app/lr/run/$attemptId'
    | '/_app/speaking/result/$attemptId'
    | '/_app/writing/result/$attemptId'
    | '/_app/writing/task/$promptId'
    | '/_app/admin/replays/'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mistakes': {
      id: '/_app/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/styleguide': {
      id: '/_app/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof AppStyleguideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/content': {
      id: '/_app/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/costs': {
      id: '/_app/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AppAdminCostsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/feedback': {
      id: '/_app/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AppAdminFeedbackRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/funnel': {
      id: '/_app/admin/funnel'
      path: '/funnel'
      fullPath: '/admin/funnel'
      preLoaderRoute: typeof AppAdminFunnelRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/growth': {
      id: '/_app/admin/growth'
      path: '/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AppAdminGrowthRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/health': {
      id: '/_app/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AppAdminHealthRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/tests': {
      id: '/_app/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AppAdminTestsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/listening/': {
      id: '/_app/listening/'
      path: '/listening'
      fullPath: '/listening/'
      preLoaderRoute: typeof AppListeningIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading/': {
      id: '/_app/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof AppReadingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/': {
      id: '/_app/speaking/'
      path: '/speaking'
      fullPath: '/speaking/'
      preLoaderRoute: typeof AppSpeakingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/live': {
      id: '/_app/speaking/live'
      path: '/speaking/live'
      fullPath: '/speaking/live'
      preLoaderRoute: typeof AppSpeakingLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/session': {
      id: '/_app/speaking/session'
      path: '/speaking/session'
      fullPath: '/speaking/session'
      preLoaderRoute: typeof AppSpeakingSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/': {
      id: '/_app/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof AppWritingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/full': {
      id: '/_app/writing/full'
      path: '/writing/full'
      fullPath: '/writing/full'
      preLoaderRoute: typeof AppWritingFullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/replays/': {
      id: '/_app/admin/replays/'
      path: '/replays'
      fullPath: '/admin/replays/'
      preLoaderRoute: typeof AppAdminReplaysIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/replays/$sessionId': {
      id: '/_app/admin/replays/$sessionId'
      path: '/replays/$sessionId'
      fullPath: '/admin/replays/$sessionId'
      preLoaderRoute: typeof AppAdminReplaysSessionIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/lr/result/$attemptId': {
      id: '/_app/lr/result/$attemptId'
      path: '/lr/result/$attemptId'
      fullPath: '/lr/result/$attemptId'
      preLoaderRoute: typeof AppLrResultAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lr/run/$attemptId': {
      id: '/_app/lr/run/$attemptId'
      path: '/lr/run/$attemptId'
      fullPath: '/lr/run/$attemptId'
      preLoaderRoute: typeof AppLrRunAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/result/$attemptId': {
      id: '/_app/speaking/result/$attemptId'
      path: '/speaking/result/$attemptId'
      fullPath: '/speaking/result/$attemptId'
      preLoaderRoute: typeof AppSpeakingResultAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/result/$attemptId': {
      id: '/_app/writing/result/$attemptId'
      path: '/writing/result/$attemptId'
      fullPath: '/writing/result/$attemptId'
      preLoaderRoute: typeof AppWritingResultAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/task/$promptId': {
      id: '/_app/writing/task/$promptId'
      path: '/writing/task/$promptId'
      fullPath: '/writing/task/$promptId'
      preLoaderRoute: typeof AppWritingTaskPromptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminCostsRoute: typeof AppAdminCostsRoute
  AppAdminFeedbackRoute: typeof AppAdminFeedbackRoute
  AppAdminFunnelRoute: typeof AppAdminFunnelRoute
  AppAdminGrowthRoute: typeof AppAdminGrowthRoute
  AppAdminHealthRoute: typeof AppAdminHealthRoute
  AppAdminTestsRoute: typeof AppAdminTestsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminReplaysSessionIdRoute: typeof AppAdminReplaysSessionIdRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminReplaysIndexRoute: typeof AppAdminReplaysIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminCostsRoute: AppAdminCostsRoute,
  AppAdminFeedbackRoute: AppAdminFeedbackRoute,
  AppAdminFunnelRoute: AppAdminFunnelRoute,
  AppAdminGrowthRoute: AppAdminGrowthRoute,
  AppAdminHealthRoute: AppAdminHealthRoute,
  AppAdminTestsRoute: AppAdminTestsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminReplaysSessionIdRoute: AppAdminReplaysSessionIdRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminReplaysIndexRoute: AppAdminReplaysIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBankRoute: typeof AppBankRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMistakesRoute: typeof AppMistakesRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStyleguideRoute: typeof AppStyleguideRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSpeakingLiveRoute: typeof AppSpeakingLiveRoute
  AppSpeakingSessionRoute: typeof AppSpeakingSessionRoute
  AppWritingFullRoute: typeof AppWritingFullRoute
  AppListeningIndexRoute: typeof AppListeningIndexRoute
  AppReadingIndexRoute: typeof AppReadingIndexRoute
  AppSpeakingIndexRoute: typeof AppSpeakingIndexRoute
  AppWritingIndexRoute: typeof AppWritingIndexRoute
  AppLrResultAttemptIdRoute: typeof AppLrResultAttemptIdRoute
  AppLrRunAttemptIdRoute: typeof AppLrRunAttemptIdRoute
  AppSpeakingResultAttemptIdRoute: typeof AppSpeakingResultAttemptIdRoute
  AppWritingResultAttemptIdRoute: typeof AppWritingResultAttemptIdRoute
  AppWritingTaskPromptIdRoute: typeof AppWritingTaskPromptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBankRoute: AppBankRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMistakesRoute: AppMistakesRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStyleguideRoute: AppStyleguideRoute,
  AppIndexRoute: AppIndexRoute,
  AppSpeakingLiveRoute: AppSpeakingLiveRoute,
  AppSpeakingSessionRoute: AppSpeakingSessionRoute,
  AppWritingFullRoute: AppWritingFullRoute,
  AppListeningIndexRoute: AppListeningIndexRoute,
  AppReadingIndexRoute: AppReadingIndexRoute,
  AppSpeakingIndexRoute: AppSpeakingIndexRoute,
  AppWritingIndexRoute: AppWritingIndexRoute,
  AppLrResultAttemptIdRoute: AppLrResultAttemptIdRoute,
  AppLrRunAttemptIdRoute: AppLrRunAttemptIdRoute,
  AppSpeakingResultAttemptIdRoute: AppSpeakingResultAttemptIdRoute,
  AppWritingResultAttemptIdRoute: AppWritingResultAttemptIdRoute,
  AppWritingTaskPromptIdRoute: AppWritingTaskPromptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
