/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppMistakesRouteImport } from './routes/_app/mistakes'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStyleguideRouteImport } from './routes/_app/styleguide'
import { Route as AppSpeakingIndexRouteImport } from './routes/_app/speaking/index'
import { Route as AppSpeakingLiveRouteImport } from './routes/_app/speaking/live'
import { Route as AppSpeakingSessionRouteImport } from './routes/_app/speaking/session'
import { Route as AppWritingIndexRouteImport } from './routes/_app/writing/index'
import { Route as AppWritingFullRouteImport } from './routes/_app/writing/full'
import { Route as AppSpeakingResultAttemptIdRouteImport } from './routes/_app/speaking/result.$attemptId'
import { Route as AppWritingResultAttemptIdRouteImport } from './routes/_app/writing/result.$attemptId'
import { Route as AppWritingTaskPromptIdRouteImport } from './routes/_app/writing/task.$promptId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStyleguideRoute = AppStyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingIndexRoute = AppSpeakingIndexRouteImport.update({
  id: '/speaking/',
  path: '/speaking/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingLiveRoute = AppSpeakingLiveRouteImport.update({
  id: '/speaking/live',
  path: '/speaking/live',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingSessionRoute = AppSpeakingSessionRouteImport.update({
  id: '/speaking/session',
  path: '/speaking/session',
  getParentRoute: () => AppRoute,
} as any)
const AppWritingIndexRoute = AppWritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => AppRoute,
} as any)
const AppWritingFullRoute = AppWritingFullRouteImport.update({
  id: '/writing/full',
  path: '/writing/full',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingResultAttemptIdRoute =
  AppSpeakingResultAttemptIdRouteImport.update({
    id: '/speaking/result/$attemptId',
    path: '/speaking/result/$attemptId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWritingResultAttemptIdRoute =
  AppWritingResultAttemptIdRouteImport.update({
    id: '/writing/result/$attemptId',
    path: '/writing/result/$attemptId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWritingTaskPromptIdRoute = AppWritingTaskPromptIdRouteImport.update({
  id: '/writing/task/$promptId',
  path: '/writing/task/$promptId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bank': typeof AppBankRoute
  '/history': typeof AppHistoryRoute
  '/mistakes': typeof AppMistakesRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/styleguide': typeof AppStyleguideRoute
  '/speaking/live': typeof AppSpeakingLiveRoute
  '/speaking/session': typeof AppSpeakingSessionRoute
  '/writing/full': typeof AppWritingFullRoute
  '/speaking/': typeof AppSpeakingIndexRoute
  '/writing/': typeof AppWritingIndexRoute
  '/speaking/result/$attemptId': typeof AppSpeakingResultAttemptIdRoute
  '/writing/result/$attemptId': typeof AppWritingResultAttemptIdRoute
  '/writing/task/$promptId': typeof AppWritingTaskPromptIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bank': typeof AppBankRoute
  '/history': typeof AppHistoryRoute
  '/mistakes': typeof AppMistakesRoute
  '/review': typeof AppReviewRoute
  '/settings': typeof AppSettingsRoute
  '/styleguide': typeof AppStyleguideRoute
  '/': typeof AppIndexRoute
  '/speaking/live': typeof AppSpeakingLiveRoute
  '/speaking/session': typeof AppSpeakingSessionRoute
  '/writing/full': typeof AppWritingFullRoute
  '/speaking': typeof AppSpeakingIndexRoute
  '/writing': typeof AppWritingIndexRoute
  '/speaking/result/$attemptId': typeof AppSpeakingResultAttemptIdRoute
  '/writing/result/$attemptId': typeof AppWritingResultAttemptIdRoute
  '/writing/task/$promptId': typeof AppWritingTaskPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/mistakes': typeof AppMistakesRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/styleguide': typeof AppStyleguideRoute
  '/_app/': typeof AppIndexRoute
  '/_app/speaking/live': typeof AppSpeakingLiveRoute
  '/_app/speaking/session': typeof AppSpeakingSessionRoute
  '/_app/writing/full': typeof AppWritingFullRoute
  '/_app/speaking/': typeof AppSpeakingIndexRoute
  '/_app/writing/': typeof AppWritingIndexRoute
  '/_app/speaking/result/$attemptId': typeof AppSpeakingResultAttemptIdRoute
  '/_app/writing/result/$attemptId': typeof AppWritingResultAttemptIdRoute
  '/_app/writing/task/$promptId': typeof AppWritingTaskPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/bank'
    | '/history'
    | '/mistakes'
    | '/review'
    | '/settings'
    | '/styleguide'
    | '/speaking/live'
    | '/speaking/session'
    | '/writing/full'
    | '/speaking/'
    | '/writing/'
    | '/speaking/result/$attemptId'
    | '/writing/result/$attemptId'
    | '/writing/task/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/bank'
    | '/history'
    | '/mistakes'
    | '/review'
    | '/settings'
    | '/styleguide'
    | '/'
    | '/speaking/live'
    | '/speaking/session'
    | '/writing/full'
    | '/speaking'
    | '/writing'
    | '/speaking/result/$attemptId'
    | '/writing/result/$attemptId'
    | '/writing/task/$promptId'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/bank'
    | '/_app/history'
    | '/_app/mistakes'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/styleguide'
    | '/_app/'
    | '/_app/speaking/live'
    | '/_app/speaking/session'
    | '/_app/writing/full'
    | '/_app/speaking/'
    | '/_app/writing/'
    | '/_app/speaking/result/$attemptId'
    | '/_app/writing/result/$attemptId'
    | '/_app/writing/task/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mistakes': {
      id: '/_app/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/styleguide': {
      id: '/_app/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof AppStyleguideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/': {
      id: '/_app/speaking/'
      path: '/speaking'
      fullPath: '/speaking/'
      preLoaderRoute: typeof AppSpeakingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/live': {
      id: '/_app/speaking/live'
      path: '/speaking/live'
      fullPath: '/speaking/live'
      preLoaderRoute: typeof AppSpeakingLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/session': {
      id: '/_app/speaking/session'
      path: '/speaking/session'
      fullPath: '/speaking/session'
      preLoaderRoute: typeof AppSpeakingSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/': {
      id: '/_app/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof AppWritingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/full': {
      id: '/_app/writing/full'
      path: '/writing/full'
      fullPath: '/writing/full'
      preLoaderRoute: typeof AppWritingFullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking/result/$attemptId': {
      id: '/_app/speaking/result/$attemptId'
      path: '/speaking/result/$attemptId'
      fullPath: '/speaking/result/$attemptId'
      preLoaderRoute: typeof AppSpeakingResultAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/result/$attemptId': {
      id: '/_app/writing/result/$attemptId'
      path: '/writing/result/$attemptId'
      fullPath: '/writing/result/$attemptId'
      preLoaderRoute: typeof AppWritingResultAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing/task/$promptId': {
      id: '/_app/writing/task/$promptId'
      path: '/writing/task/$promptId'
      fullPath: '/writing/task/$promptId'
      preLoaderRoute: typeof AppWritingTaskPromptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBankRoute: typeof AppBankRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMistakesRoute: typeof AppMistakesRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStyleguideRoute: typeof AppStyleguideRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSpeakingLiveRoute: typeof AppSpeakingLiveRoute
  AppSpeakingSessionRoute: typeof AppSpeakingSessionRoute
  AppWritingFullRoute: typeof AppWritingFullRoute
  AppSpeakingIndexRoute: typeof AppSpeakingIndexRoute
  AppWritingIndexRoute: typeof AppWritingIndexRoute
  AppSpeakingResultAttemptIdRoute: typeof AppSpeakingResultAttemptIdRoute
  AppWritingResultAttemptIdRoute: typeof AppWritingResultAttemptIdRoute
  AppWritingTaskPromptIdRoute: typeof AppWritingTaskPromptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankRoute: AppBankRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMistakesRoute: AppMistakesRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStyleguideRoute: AppStyleguideRoute,
  AppIndexRoute: AppIndexRoute,
  AppSpeakingLiveRoute: AppSpeakingLiveRoute,
  AppSpeakingSessionRoute: AppSpeakingSessionRoute,
  AppWritingFullRoute: AppWritingFullRoute,
  AppSpeakingIndexRoute: AppSpeakingIndexRoute,
  AppWritingIndexRoute: AppWritingIndexRoute,
  AppSpeakingResultAttemptIdRoute: AppSpeakingResultAttemptIdRoute,
  AppWritingResultAttemptIdRoute: AppWritingResultAttemptIdRoute,
  AppWritingTaskPromptIdRoute: AppWritingTaskPromptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
