/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, settings and feature access */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Effective settings (user overrides merged over defaults) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** Update settings (partial; models merge per key) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsPatch"];
                };
            };
            responses: {
                /** @description Effective settings (user overrides merged over defaults) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenRouter models (cached 1 h), optionally filtered by capability */
        get: {
            parameters: {
                query?: {
                    capability?: "text" | "audio-in" | "stt" | "tts";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Models */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelList"];
                    };
                };
                /** @description OpenRouter unavailable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompt bank (30 per page) with a per-user done flag */
        get: {
            parameters: {
                query?: {
                    skill?: "speaking" | "writing";
                    part?: number;
                    variant?: "academic" | "general";
                    type?: string;
                    topic?: string;
                    source?: "generated" | "cambridge";
                    q?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PromptPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distinct topics and types per skill/part (for bank filters) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Filter values */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PromptMeta"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A random matching prompt, preferring ones the user has not done */
        get: {
            parameters: {
                query: {
                    skill: "speaking" | "writing";
                    part?: number;
                    variant?: "academic" | "general";
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Prompt"];
                    };
                };
                /** @description No matching prompt */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single prompt (figure URL presigned) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Prompt"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/speaking/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Random full speaking test: 3 P1 topics × 4 questions, a P2 cue card and its linked P3 */
        get: {
            parameters: {
                query?: {
                    source?: "generated" | "cambridge" | "any";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeakingTest"];
                    };
                };
                /** @description Bank is empty */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attempt history, newest first, 20 per page */
        get: {
            parameters: {
                query?: {
                    skill?: "speaking" | "writing";
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attempts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptList"];
                    };
                };
            };
        };
        put?: never;
        /** Create an attempt (speaking: returns a presigned audio upload URL) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttempt"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedAttempt"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an attempt for analysis (also re-runs a failed one). Returns immediately; poll GET /api/attempts/{id}. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitAttempt"];
                };
            };
            responses: {
                /** @description Analysis started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "analyzing";
                        };
                    };
                };
                /** @description Upload missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Already submitted */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attempt with analysis, presigned audio URL and prompt (poll until status is done|failed) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attempt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Attempt"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete an attempt (its analysis and mistakes cascade) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a live examiner session: picks a full speaking test and returns the opening line with TTS audio */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveStart"];
                };
            };
            responses: {
                /** @description Session started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveStarted"];
                    };
                };
                /** @description Bank is empty */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description AI service error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presigned PUT for a candidate recording (a turn or a whole part) in this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveUploadUrl"];
                };
            };
            responses: {
                /** @description Upload URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveUpload"];
                    };
                };
                /** @description Bad type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn-based examiner: transcribes the candidate's answer (if any) and returns the examiner's next line */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveTurn"];
                };
            };
            responses: {
                /** @description Next examiner line */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExaminerLine"];
                    };
                };
                /** @description Bad audio key */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Test already over */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description AI service error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/realtime-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ephemeral OpenAI Realtime client secret carrying the examiner instructions for this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveRealtimeToken"];
                };
            };
            responses: {
                /** @description Client secret */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RealtimeToken"];
                    };
                };
                /** @description Realtime not configured */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description OpenAI error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish a live session: one attempt per recorded part (mode live, shared sessionId), each analysed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveFinish"];
                };
            };
            responses: {
                /** @description Attempts created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveFinished"];
                    };
                };
                /** @description Bad upload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Already finished */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard stats: band trend, streak, minutes, weakest criterion, recurring mistakes, predicted band */
        get: {
            parameters: {
                query?: {
                    skill?: "speaking" | "writing";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Progress */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Progress"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mistakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error log: counts per category + newest mistakes (optionally one category), 30 per page */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mistakes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MistakeLog"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mistakes/{id}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a mistake to the review deck (front: original, back: correction — explanation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a card to the review deck */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CardInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add several cards at once (e.g. all top fixes of a result) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        cards: components["schemas"]["CardInput"][];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cards: components["schemas"]["Card"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards due for review now (oldest due first, max 50) and the total due count */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Due cards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DueCards"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade a card (SM-2: 0-2 again, 3 hard, 4 good, 5 easy) and reschedule it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CardReview"];
                };
            };
            responses: {
                /** @description Rescheduled card */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            user: {
                id: string;
                email: string;
                name: string;
                emailVerified: boolean;
            };
            settings: {
                models: {
                    analysis: string;
                    examiner: string;
                    stt: string;
                    tts: string;
                    ttsVoice: string;
                    audioPron: string;
                };
                audioPronEnabled: boolean;
                /** @enum {string} */
                liveProvider: "turn" | "openai-realtime";
                targetBand: number;
                writingAutoSubmit: boolean;
                blockPaste: boolean;
            };
            cambridgeAccess: boolean;
            realtimeAvailable: boolean;
        };
        Settings: {
            models: {
                analysis: string;
                examiner: string;
                stt: string;
                tts: string;
                ttsVoice: string;
                audioPron: string;
            };
            audioPronEnabled: boolean;
            /** @enum {string} */
            liveProvider: "turn" | "openai-realtime";
            targetBand: number;
            writingAutoSubmit: boolean;
            blockPaste: boolean;
        };
        SettingsPatch: {
            models?: {
                analysis?: string;
                examiner?: string;
                stt?: string;
                tts?: string;
                ttsVoice?: string;
                audioPron?: string;
            };
            audioPronEnabled?: boolean;
            /** @enum {string} */
            liveProvider?: "turn" | "openai-realtime";
            targetBand?: number;
            writingAutoSubmit?: boolean;
            blockPaste?: boolean;
        };
        ModelList: {
            models: components["schemas"]["Model"][];
        };
        Model: {
            id: string;
            name: string;
            input: string[];
            output: string[];
            /** @description USD per token, as strings */
            pricing: {
                prompt: string;
                completion: string;
            };
            /** @description TTS voices the model supports (empty for non-speech models) */
            voices: string[];
        };
        PromptPage: {
            items: components["schemas"]["Prompt"][];
            total: number;
            page: number;
            pageSize: number;
        };
        Prompt: {
            id: string;
            slug: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string|null} */
            variant: "academic" | "general" | null;
            type: string;
            topic: string;
            title: string;
            body: string;
            bullets: string[] | null;
            followUps: string[] | null;
            /** @description ChartSpec (generated Academic Task 1) */
            chart?: unknown;
            /** @description Presigned figure URL (Cambridge Task 1) */
            imageUrl: string | null;
            /** @enum {string} */
            source: "generated" | "cambridge";
            sourceRef: string | null;
            groupId: string | null;
            /** @description The user has an attempt on this prompt */
            done: boolean;
        };
        PromptMeta: {
            groups: {
                /** @enum {string} */
                skill: "speaking" | "writing";
                part: number;
                topics: string[];
                types: string[];
            }[];
        };
        Error: {
            error: string;
        };
        SpeakingTest: {
            part1: components["schemas"]["Prompt"][];
            part2: components["schemas"]["Prompt"];
            part3: components["schemas"]["Prompt"];
        };
        CreatedAttempt: {
            id: string;
            /** @description Presigned PUT (speaking). Send the same Content-Type as audioContentType. */
            uploadUrl?: string;
            audioKey?: string;
        };
        CreateAttempt: {
            promptId: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /**
             * @default practice
             * @enum {string}
             */
            mode: "practice" | "live" | "exam";
            sessionId?: string;
            parentAttemptId?: string;
            text?: string;
            /** @description Speaking only: audio/webm | audio/mp4 | audio/m4a | audio/wav (codec params allowed). Default audio/webm. */
            audioContentType?: string;
        };
        SubmitAttempt: {
            /** @description Speaking: recording length. Writing: time spent in the editor (counts toward weekly minutes). */
            durationMs?: number;
            /** @description 50 ms RMS frames, 0-255 */
            energy?: number[];
            /** @description Question start offsets (ms) */
            marks?: number[];
            text?: string;
            plan?: string;
            overtime?: boolean;
        };
        Attempt: {
            id: string;
            promptId: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string} */
            mode: "practice" | "live" | "exam";
            sessionId: string | null;
            parentAttemptId: string | null;
            audioMime: string | null;
            audioUrl: string | null;
            text: string | null;
            plan: string | null;
            energy: number[] | null;
            marks: number[] | null;
            durationMs: number | null;
            overtime: boolean;
            /** @enum {string} */
            status: "recording" | "analyzing" | "done" | "failed";
            error: string | null;
            /** @description status failed: false when retrying now cannot help (AI credit/key problem); show "try later" instead of Retry */
            retryable: boolean;
            createdAt: string;
            /**
             * @description While analyzing: the pipeline step now running. writing: feedback → scoring (feedback is ready in `partial`) → finalizing; speaking: transcribing → analyzing → finalizing. null once done|failed or before the first step.
             * @enum {string|null}
             */
            stage: "transcribing" | "analyzing" | "feedback" | "scoring" | "finalizing" | null;
            /** @description Writing, while stage is scoring: the feedback that is ready before the scores (errors, structure, top fixes, vocab upgrades, rewrite, text metrics: AnalysisResult fields without criteria/overall). null otherwise. */
            partial?: unknown;
            /** @description AnalysisResult (spec §6) once status is done */
            analysis?: unknown;
            /** @description OpenRouter models that produced the analysis, by role (stt, analysis, audioPron); null until done */
            models: {
                [key: string]: string;
            } | null;
            /** @description Every top fix is already in the review deck (as POST /api/cards/bulk with source 'fix' adds them) */
            topFixesInDeck: boolean;
            prompt: components["schemas"]["AttemptPrompt"];
        };
        AttemptPrompt: {
            id: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string|null} */
            variant: "academic" | "general" | null;
            type: string;
            topic: string;
            title: string;
            body: string;
            bullets: string[] | null;
            followUps: string[] | null;
            chart?: unknown;
            imageUrl: string | null;
            groupId: string | null;
        };
        AttemptList: {
            items: components["schemas"]["AttemptListItem"][];
            page: number;
            pageSize: number;
            total: number;
        };
        AttemptListItem: {
            id: string;
            promptId: string;
            promptTitle: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string} */
            mode: "practice" | "live" | "exam";
            sessionId: string | null;
            /** @enum {string} */
            status: "recording" | "analyzing" | "done" | "failed";
            durationMs: number | null;
            overall: number | null;
            createdAt: string;
        };
        LiveStarted: components["schemas"]["ExaminerLine"] & {
            sessionId: string;
            test: {
                part1: components["schemas"]["Prompt"][];
                part2: components["schemas"]["Prompt"];
                part3: components["schemas"]["Prompt"];
            };
        };
        ExaminerLine: {
            examinerText: string;
            /** @description Examiner TTS; null when the voice failed or was skipped: show examinerText as a caption and start listening */
            audioUrl: string | null;
            /** @description Why audioUrl is null (voice failed) */
            voiceError?: string;
            /**
             * @description Phase of this line; 'done' after the closing line
             * @enum {string}
             */
            phase: "intro" | "p1" | "p2-prep" | "p2-talk" | "p2-follow" | "p3" | "closing" | "done";
            /** @description The candidate's transcribed answer */
            transcript?: string;
            /** @description p2-prep: seconds of preparation left; POST /turn (skipped) when it ends */
            prepSeconds?: number;
            cueCard?: components["schemas"]["Prompt"];
        };
        LiveStart: {
            /**
             * @default any
             * @enum {string}
             */
            source: "generated" | "cambridge" | "any";
            /**
             * @description Realtime sessions speak for themselves: create the session without examiner TTS (audioUrl null)
             * @default false
             */
            skipTts: boolean;
        };
        LiveUpload: {
            key: string;
            uploadUrl: string;
        };
        LiveUploadUrl: {
            sessionId: string;
            /** @default audio/webm */
            audioContentType: string;
        };
        LiveTurn: {
            sessionId: string;
            audioKey?: string;
            skipped?: boolean;
        };
        RealtimeToken: {
            value: string;
            /** @description Unix seconds */
            expiresAt: number;
            model: string;
        };
        LiveRealtimeToken: {
            sessionId: string;
        };
        LiveFinished: {
            attemptIds: string[];
        };
        LiveFinish: {
            sessionId: string;
            parts: {
                part: 1 | 2 | 3;
                audioKey: string;
                durationMs: number;
                energy?: number[];
                /** @description Question start offsets (ms) within this part */
                marks?: number[];
            }[];
        };
        Progress: {
            /** @description Last 30 analysed attempts, oldest first */
            trend: {
                attemptId: string;
                date: string;
                /** @enum {string} */
                skill: "speaking" | "writing";
                part: number;
                overall: number;
                criteria: {
                    [key: string]: number;
                };
            }[];
            streak: number;
            minutesThisWeek: number;
            /** @description Analysed attempts */
            attempts: number;
            weakest: {
                key: string;
                avg: number;
            } | null;
            /** @description Top 5 categories, last 30 days */
            topMistakes: {
                category: string;
                count: number;
            }[];
            /** @description roundBand of the mean of the last 5 overalls per skill (ignores the skill filter) */
            predicted: {
                speaking: number | null;
                writing: number | null;
            };
            /** @description The user's most recent submitted attempt, when its analysis failed */
            lastFailed: {
                id: string;
                /** @enum {string} */
                skill: "speaking" | "writing";
            } | null;
        };
        MistakeLog: {
            /** @description All categories, most frequent first */
            groups: {
                category: string;
                count: number;
            }[];
            items: components["schemas"]["Mistake"][];
            total: number;
            page: number;
            pageSize: number;
        };
        Mistake: {
            id: string;
            attemptId: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            promptTitle: string;
            category: string;
            original: string;
            correction: string;
            explanation: string;
            /** @description Seconds into the audio (speaking) */
            time: number | null;
            /** @description Already added to the review deck */
            inDeck: boolean;
            createdAt: string;
        };
        Card: components["schemas"]["CardInput"] & {
            id: string;
            ease: number;
            /** @description Days */
            interval: number;
            reps: number;
            due: string;
            createdAt: string;
        };
        CardInput: {
            front: string;
            back: string;
            /** @enum {string} */
            source: "mistake" | "vocab" | "fix";
        };
        DueCards: {
            cards: components["schemas"]["Card"][];
            total: number;
        };
        CardReview: {
            grade: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
