/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, settings and feature access */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Effective settings (user overrides merged over defaults) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** Update settings (partial; models merge per key) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SettingsPatch"];
                };
            };
            responses: {
                /** @description Effective settings (user overrides merged over defaults) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenRouter models (cached 1 h), optionally filtered by capability */
        get: {
            parameters: {
                query?: {
                    capability?: "text" | "audio-in" | "stt" | "tts";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Models */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelList"];
                    };
                };
                /** @description OpenRouter unavailable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompt bank (30 per page) with a per-user done flag */
        get: {
            parameters: {
                query?: {
                    skill?: "speaking" | "writing";
                    part?: number;
                    variant?: "academic" | "general";
                    type?: string;
                    topic?: string;
                    source?: "generated" | "cambridge";
                    q?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PromptPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distinct topics and types per skill/part (for bank filters) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Filter values */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PromptMeta"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A random matching prompt, preferring ones the user has not done */
        get: {
            parameters: {
                query: {
                    skill: "speaking" | "writing";
                    part?: number;
                    variant?: "academic" | "general";
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Prompt"];
                    };
                };
                /** @description No matching prompt */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single prompt (figure URL presigned) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Prompt"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/speaking/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Random full speaking test: 3 P1 topics × 4 questions, a P2 cue card and its linked P3 */
        get: {
            parameters: {
                query?: {
                    source?: "generated" | "cambridge" | "any";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpeakingTest"];
                    };
                };
                /** @description Bank is empty */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attempt history, newest first, 20 per page */
        get: {
            parameters: {
                query?: {
                    skill?: "speaking" | "writing";
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attempts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptList"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an attempt (speaking: returns a presigned audio upload URL)
         * @description Also checks the quota first (nothing is reserved yet), so a person out of tests hears before writing the essay: 429 quota_exceeded, 402 community_balance_exhausted, 503 community_busy. docs/community.md
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttempt"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedAttempt"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description community_balance_exhausted */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description quota_exceeded (or too_many_requests) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description community_busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an attempt for analysis (also re-runs a failed one). Returns immediately; poll GET /api/attempts/{id}.
         * @description Reserves the test against the quota (one per speaking/writing session; re-submitting the same attempt never costs again; refunded if analysis fails or no speech is heard). When refused, a writing draft sent in the body is still saved on the attempt. docs/community.md
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitAttempt"];
                };
            };
            responses: {
                /** @description Analysis started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "analyzing";
                        };
                    };
                };
                /** @description Upload missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description community_balance_exhausted */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Already submitted */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description quota_exceeded (or too_many_requests) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description community_busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightweight status for polling (no analysis, prompt or presigned URLs); fetch the full attempt when status or stage changes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttemptStatus"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attempt with analysis, presigned audio URL and prompt (poll until status is done|failed) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attempt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Attempt"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete an attempt (its analysis and mistakes cascade) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a live examiner session: picks a full speaking test and returns the opening line with TTS audio
         * @description Needs the user's own key: OpenRouter for the turn-based examiner (skipTts false), OpenAI or Gemini for duplex sessions (skipTts true), else 403 live_requires_own_key. A user without an OpenRouter key also needs a test left (429 quota_exceeded, 402 community_balance_exhausted).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveStart"];
                };
            };
            responses: {
                /** @description Session started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveStarted"];
                    };
                };
                /** @description community_balance_exhausted */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description live_requires_own_key: the live examiner runs only on the user's own OpenRouter (turn-based), OpenAI (GPT-Live) or Gemini (Gemini Live) key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Bank is empty */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests (too_many_requests), or the test quota is used up (quota_exceeded) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description AI service error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description community_busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presigned PUT for a candidate recording (a turn or a whole part) in this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveUploadUrl"];
                };
            };
            responses: {
                /** @description Upload URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveUpload"];
                    };
                };
                /** @description Bad type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn-based examiner: transcribes the candidate's answer (if any) and returns the examiner's next line */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveTurn"];
                };
            };
            responses: {
                /** @description Next examiner line */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExaminerLine"];
                    };
                };
                /** @description Bad audio key */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description live_requires_own_key: the live examiner runs only on the user's own OpenRouter (turn-based), OpenAI (GPT-Live) or Gemini (Gemini Live) key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Test already over */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests (too_many_requests), or the test quota is used up (quota_exceeded) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description AI service error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/gpt-live/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GPT-Live over WebRTC: exchanges the browser's SDP offer for the answer. The server creates the session (model, voice and examiner instructions are ours) and attaches a sideband that records the transcript */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveGptSession"];
                };
            };
            responses: {
                /** @description SDP answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GptLiveSession"];
                    };
                };
                /** @description invalid_key: OpenAI rejected the user's key */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description live_requires_own_key: the live examiner runs only on the user's own OpenRouter (turn-based), OpenAI (GPT-Live) or Gemini (Gemini Live) key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests (too_many_requests), or the test quota is used up (quota_exceeded) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description OpenAI error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/gpt-live/cue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Script control for a GPT-Live session: the server appends the instruction for this moment (session.instructions.append) through its sideband. If it could not, `content` is the instruction for the client to append on its data channel */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveGptCue"];
                };
            };
            responses: {
                /** @description Cue handled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GptLiveCueResult"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests (too_many_requests), or the test quota is used up (quota_exceeded) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/gemini-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ephemeral Gemini Live token locked to the examiner setup (model, voice, instructions, VAD) for this session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveGeminiToken"];
                };
            };
            responses: {
                /** @description Ephemeral token: pass as access_token to BidiGenerateContentConstrained */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GeminiToken"];
                    };
                };
                /** @description invalid_key: Gemini rejected the user's key */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description live_requires_own_key: the live examiner runs only on the user's own OpenRouter (turn-based), OpenAI (GPT-Live) or Gemini (Gemini Live) key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests (too_many_requests), or the test quota is used up (quota_exceeded) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Gemini error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish a live session: one attempt per recorded part (mode live, shared sessionId), each analysed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiveFinish"];
                };
            };
            responses: {
                /** @description Attempts created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveFinished"];
                    };
                };
                /** @description Bad upload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description community_balance_exhausted */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Already finished */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many requests (too_many_requests), or the test quota is used up (quota_exceeded) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description community_busy */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard stats: band trend, streak, minutes, weakest criterion, recurring mistakes, predicted band */
        get: {
            parameters: {
                query?: {
                    skill?: "speaking" | "writing";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Progress */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Progress"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mistakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error log: counts per category + newest mistakes (optionally one category), 30 per page */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mistakes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MistakeLog"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mistakes/{id}/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a mistake to the review deck (front: original, back: correction — explanation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a card to the review deck */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CardInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add several cards at once (e.g. all top fixes of a result) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        cards: components["schemas"]["CardInput"][];
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cards: components["schemas"]["Card"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards due for review now (oldest due first, max 50) and the total due count */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Due cards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DueCards"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade a card (SM-2: 0-2 again, 3 hard, 4 good, 5 easy) and reschedule it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CardReview"];
                };
            };
            responses: {
                /** @description Rescheduled card */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/community/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shared community balance (public, cached 60 s) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommunityBalance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tests left, reset times and live access for the caller. Works without a session (a guest, counted by IP). Call it when a test is about to start */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Quota */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Quota"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your saved API keys (provider, last 4 characters, date, whether it still works) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyList"];
                    };
                };
                /** @description Guests have no keys (account_required) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save (or replace) your own key for a provider. It is checked with a free live call first and stored encrypted */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "openrouter" | "openai" | "gemini";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PutApiKey"];
                };
            };
            responses: {
                /** @description Saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyInfo"];
                    };
                };
                /** @description invalid_key: the provider rejected it */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description account_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description Too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description key_check_failed: the provider could not be reached; try again */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
                /** @description keys_unavailable: the server cannot store keys (KEY_ENCRYPTION_SECRET is not set) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        post?: never;
        /** Remove your key for a provider */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "openrouter" | "openai" | "gemini";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed (also when there was none) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
                /** @description account_required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CodedError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            user: {
                id: string;
                /** @description Empty for a guest */
                email: string;
                name: string;
                emailVerified: boolean;
                /** @description A guest (anonymous session, no account yet): show "Create an account", hide keys, history and review */
                isAnonymous: boolean;
            };
            settings: {
                models: {
                    analysis: string;
                    examiner: string;
                    stt: string;
                    tts: string;
                    ttsVoice: string;
                    audioPron: string;
                };
                audioPronEnabled: boolean;
                /** @enum {string} */
                liveProvider: "turn" | "gpt-live" | "gemini-live";
                targetBand: number;
                writingAutoSubmit: boolean;
                blockPaste: boolean;
            };
            cambridgeAccess: boolean;
            /** @description This user has an OpenAI key (or is the owner) */
            gptLiveAvailable: boolean;
            /**
             * @deprecated
             * @description Deprecated alias of gptLiveAvailable (app versions from before GPT-Live)
             */
            realtimeAvailable: boolean;
            /** @description This user has a Gemini key (or is the owner) */
            geminiLiveAvailable: boolean;
            /** @enum {string} */
            tier: "guest" | "community" | "own-key";
            speaking: components["schemas"]["SkillQuota"];
            writing: components["schemas"]["SkillQuota"];
            /** @description Live examiner providers this user may use (their own keys; the owner may use the server keys) */
            liveProviders: ("turn" | "gpt-live" | "gemini-live")[];
            communityBalance: components["schemas"]["CommunityBalance"];
        };
        SkillQuota: {
            used: number;
            /** @description Tests per window; null = unlimited */
            limit: number | null;
            remaining: number | null;
            /** @description ISO instant the window resets; show in local time. null when unlimited */
            resetAt: string | null;
            /**
             * @description day: resets 00:00 UTC; week: resets Monday 00:00 UTC
             * @enum {string|null}
             */
            window: "day" | "week" | null;
            /**
             * @description Why a test cannot start now; null = it can
             * @enum {string|null}
             */
            blocked: "quota_exceeded" | "community_balance_exhausted" | "community_busy" | null;
        };
        CommunityBalance: {
            /** @description USD spend limit of the shared OpenRouter key; null if it has none */
            limit: number | null;
            /** @description USD spent so far; null if unknown */
            used: number | null;
            /** @description USD left; null if unknown or unlimited */
            remaining: number | null;
            /** @description ISO time of the reading (cached up to 60 s) */
            updatedAt: string;
        };
        Settings: {
            models: {
                analysis: string;
                examiner: string;
                stt: string;
                tts: string;
                ttsVoice: string;
                audioPron: string;
            };
            audioPronEnabled: boolean;
            /** @enum {string} */
            liveProvider: "turn" | "gpt-live" | "gemini-live";
            targetBand: number;
            writingAutoSubmit: boolean;
            blockPaste: boolean;
        };
        SettingsPatch: {
            models?: {
                analysis?: string;
                examiner?: string;
                stt?: string;
                tts?: string;
                ttsVoice?: string;
                audioPron?: string;
            };
            audioPronEnabled?: boolean;
            /** @enum {string} */
            liveProvider?: "turn" | "gpt-live" | "gemini-live";
            targetBand?: number;
            writingAutoSubmit?: boolean;
            blockPaste?: boolean;
        };
        ModelList: {
            models: components["schemas"]["Model"][];
        };
        Model: {
            id: string;
            name: string;
            input: string[];
            output: string[];
            /** @description USD per token, as strings */
            pricing: {
                prompt: string;
                completion: string;
            };
            /** @description TTS voices the model supports (empty for non-speech models) */
            voices: string[];
        };
        PromptPage: {
            items: components["schemas"]["Prompt"][];
            total: number;
            page: number;
            pageSize: number;
        };
        Prompt: {
            id: string;
            slug: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string|null} */
            variant: "academic" | "general" | null;
            type: string;
            topic: string;
            title: string;
            body: string;
            bullets: string[] | null;
            followUps: string[] | null;
            /** @description ChartSpec (generated Academic Task 1) */
            chart?: unknown;
            /** @description Presigned figure URL (Cambridge Task 1) */
            imageUrl: string | null;
            /** @enum {string} */
            source: "generated" | "cambridge";
            sourceRef: string | null;
            groupId: string | null;
            /** @description The user has an attempt on this prompt */
            done: boolean;
        };
        PromptMeta: {
            groups: {
                /** @enum {string} */
                skill: "speaking" | "writing";
                part: number;
                topics: string[];
                types: string[];
            }[];
        };
        Error: {
            error: string;
        };
        SpeakingTest: {
            part1: components["schemas"]["Prompt"][];
            part2: components["schemas"]["Prompt"];
            part3: components["schemas"]["Prompt"];
        };
        CreatedAttempt: {
            id: string;
            /** @description Presigned PUT (speaking). Send the same Content-Type as audioContentType. */
            uploadUrl?: string;
            audioKey?: string;
        };
        /** @description Errors with a machine-readable code (docs/community.md). Map `code` to UX; `error` is a fallback. */
        CodedError: {
            /** @description Friendly, safe to show */
            error: string;
            /** @enum {string} */
            code: "quota_exceeded" | "community_balance_exhausted" | "community_busy" | "too_many_requests" | "live_requires_own_key" | "account_required" | "keys_unavailable" | "invalid_key" | "key_check_failed";
            /**
             * @description quota_exceeded
             * @enum {string}
             */
            skill?: "speaking" | "writing";
            /** @description quota_exceeded: ISO time the window resets (00:00 UTC daily, Monday 00:00 UTC weekly) */
            resetAt?: string | null;
            /**
             * @description quota_exceeded, live_requires_own_key
             * @enum {string}
             */
            tier?: "guest" | "community" | "own-key";
        };
        CreateAttempt: {
            promptId: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /**
             * @default practice
             * @enum {string}
             */
            mode: "practice" | "live" | "exam";
            sessionId?: string;
            parentAttemptId?: string;
            text?: string;
            /** @description Speaking only: audio/webm | audio/mp4 | audio/m4a | audio/wav (codec params allowed). Default audio/webm. */
            audioContentType?: string;
        };
        SubmitAttempt: {
            /** @description Speaking: recording length. Writing: time spent in the editor (counts toward weekly minutes). */
            durationMs?: number;
            /** @description 50 ms RMS frames, 0-255 */
            energy?: number[];
            /** @description Question start offsets (ms) */
            marks?: number[];
            text?: string;
            plan?: string;
            overtime?: boolean;
        };
        AttemptStatus: {
            /** @enum {string} */
            status: "recording" | "analyzing" | "done" | "failed";
            /** @enum {string|null} */
            stage: "transcribing" | "analyzing" | "feedback" | "scoring" | "finalizing" | null;
            error: string | null;
            retryable: boolean;
        };
        Attempt: {
            id: string;
            promptId: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string} */
            mode: "practice" | "live" | "exam";
            sessionId: string | null;
            parentAttemptId: string | null;
            audioMime: string | null;
            audioUrl: string | null;
            text: string | null;
            plan: string | null;
            energy: number[] | null;
            marks: number[] | null;
            durationMs: number | null;
            overtime: boolean;
            /** @enum {string} */
            status: "recording" | "analyzing" | "done" | "failed";
            error: string | null;
            /** @description status failed: false when retrying now cannot help (AI credit/key problem); show "try later" instead of Retry */
            retryable: boolean;
            createdAt: string;
            /**
             * @description While analyzing: the pipeline step now running. writing: feedback → scoring (feedback is ready in `partial`) → finalizing; speaking: transcribing → analyzing → finalizing. null once done|failed or before the first step.
             * @enum {string|null}
             */
            stage: "transcribing" | "analyzing" | "feedback" | "scoring" | "finalizing" | null;
            /** @description Writing, while stage is scoring: the feedback that is ready before the scores (errors, structure, top fixes, vocab upgrades, rewrite, text metrics: AnalysisResult fields without criteria/overall). null otherwise. */
            partial?: unknown;
            /** @description AnalysisResult (spec §6) once status is done */
            analysis?: unknown;
            /** @description OpenRouter models that produced the analysis, by role (stt, analysis, audioPron); null until done */
            models: {
                [key: string]: string;
            } | null;
            /** @description Every top fix is already in the review deck (as POST /api/cards/bulk with source 'fix' adds them) */
            topFixesInDeck: boolean;
            prompt: components["schemas"]["AttemptPrompt"];
        };
        AttemptPrompt: {
            id: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string|null} */
            variant: "academic" | "general" | null;
            type: string;
            topic: string;
            title: string;
            body: string;
            bullets: string[] | null;
            followUps: string[] | null;
            chart?: unknown;
            imageUrl: string | null;
            groupId: string | null;
        };
        AttemptList: {
            items: components["schemas"]["AttemptListItem"][];
            page: number;
            pageSize: number;
            total: number;
        };
        AttemptListItem: {
            id: string;
            promptId: string;
            promptTitle: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            /** @enum {string} */
            mode: "practice" | "live" | "exam";
            sessionId: string | null;
            /** @enum {string} */
            status: "recording" | "analyzing" | "done" | "failed";
            durationMs: number | null;
            overall: number | null;
            createdAt: string;
        };
        LiveStarted: components["schemas"]["ExaminerLine"] & {
            sessionId: string;
            test: {
                part1: components["schemas"]["Prompt"][];
                part2: components["schemas"]["Prompt"];
                part3: components["schemas"]["Prompt"];
            };
        };
        ExaminerLine: {
            examinerText: string;
            /** @description Examiner TTS; null when the voice failed or was skipped: show examinerText as a caption and start listening */
            audioUrl: string | null;
            /** @description Why audioUrl is null (voice failed) */
            voiceError?: string;
            /**
             * @description Phase of this line; 'done' after the closing line
             * @enum {string}
             */
            phase: "intro" | "p1" | "p2-prep" | "p2-talk" | "p2-follow" | "p3" | "closing" | "done";
            /** @description The candidate's transcribed answer */
            transcript?: string;
            /** @description p2-prep: seconds of preparation left; POST /turn (skipped) when it ends */
            prepSeconds?: number;
            cueCard?: components["schemas"]["Prompt"];
        };
        LiveStart: {
            /**
             * @default any
             * @enum {string}
             */
            source: "generated" | "cambridge" | "any";
            /**
             * @description Duplex (GPT-Live, Gemini Live) sessions speak for themselves: create the session without examiner TTS (audioUrl null)
             * @default false
             */
            skipTts: boolean;
        };
        LiveUpload: {
            key: string;
            uploadUrl: string;
        };
        LiveUploadUrl: {
            sessionId: string;
            /** @default audio/webm */
            audioContentType: string;
        };
        LiveTurn: {
            sessionId: string;
            audioKey?: string;
            skipped?: boolean;
        };
        GptLiveSession: {
            sdp: string;
            /** @description OpenAI's live session id */
            sessionId: string;
        };
        LiveGptSession: {
            sessionId: string;
            /** @description The browser's SDP offer (data channel "oai-events" created before the offer) */
            sdp: string;
        };
        GptLiveCueResult: {
            sent: boolean;
            content: string;
        };
        LiveGptCue: {
            sessionId: string;
            /** @enum {string} */
            cue: "begin" | "part2" | "talk" | "follow" | "follow-timeup" | "closing";
        };
        GeminiToken: {
            value: string;
            /** @description Unix seconds */
            expiresAt: number;
            model: string;
        };
        LiveGeminiToken: {
            sessionId: string;
        };
        LiveFinished: {
            attemptIds: string[];
        };
        LiveFinish: {
            sessionId: string;
            parts: {
                part: 1 | 2 | 3;
                audioKey: string;
                durationMs: number;
                energy?: number[];
                /** @description Question start offsets (ms) within this part */
                marks?: number[];
            }[];
        };
        Progress: {
            /** @description Last 30 analysed attempts, oldest first */
            trend: {
                attemptId: string;
                date: string;
                /** @enum {string} */
                skill: "speaking" | "writing";
                part: number;
                overall: number;
                criteria: {
                    [key: string]: number;
                };
            }[];
            streak: number;
            minutesThisWeek: number;
            /** @description Analysed attempts */
            attempts: number;
            weakest: {
                key: string;
                avg: number;
            } | null;
            /** @description Top 5 categories, last 30 days */
            topMistakes: {
                category: string;
                count: number;
            }[];
            /** @description roundBand of the mean of the last 5 overalls per skill (ignores the skill filter) */
            predicted: {
                speaking: number | null;
                writing: number | null;
            };
            /** @description The user's most recent submitted attempt, when its analysis failed */
            lastFailed: {
                id: string;
                /** @enum {string} */
                skill: "speaking" | "writing";
            } | null;
        };
        MistakeLog: {
            /** @description All categories, most frequent first */
            groups: {
                category: string;
                count: number;
            }[];
            items: components["schemas"]["Mistake"][];
            total: number;
            page: number;
            pageSize: number;
        };
        Mistake: {
            id: string;
            attemptId: string;
            /** @enum {string} */
            skill: "speaking" | "writing";
            part: number;
            promptTitle: string;
            category: string;
            original: string;
            correction: string;
            explanation: string;
            /** @description Seconds into the audio (speaking) */
            time: number | null;
            /** @description Already added to the review deck */
            inDeck: boolean;
            createdAt: string;
        };
        Card: components["schemas"]["CardInput"] & {
            id: string;
            ease: number;
            /** @description Days */
            interval: number;
            reps: number;
            due: string;
            createdAt: string;
        };
        CardInput: {
            front: string;
            back: string;
            /** @enum {string} */
            source: "mistake" | "vocab" | "fix";
        };
        DueCards: {
            cards: components["schemas"]["Card"][];
            total: number;
            /** @description Total cards owned */
            deck: number;
        };
        CardReview: {
            grade: number;
        };
        Quota: {
            /** @enum {string} */
            tier: "guest" | "community" | "own-key";
            speaking: components["schemas"]["SkillQuota"];
            writing: components["schemas"]["SkillQuota"];
            /** @description Live examiner providers this user may use (their own keys; the owner may use the server keys) */
            liveProviders: ("turn" | "gpt-live" | "gemini-live")[];
            communityBalance: components["schemas"]["CommunityBalance"];
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKeyInfo"][];
        };
        /** @description The key itself is never returned. */
        ApiKeyInfo: {
            /** @enum {string} */
            provider: "openrouter" | "openai" | "gemini";
            last4: string;
            addedAt: string;
            /** @description false: the provider rejected this key; enter a new one */
            valid: boolean;
        };
        PutApiKey: {
            key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
